/*
 * Midea AC IR Blaster for ESP32-C6
 * Generated by Midea IR Decoder
 * 
 * Hardware setup:
 * - IR LED connected to GPIO pin (e.g., GPIO 18)
 * - Use appropriate current limiting resistor
 * 
 * Usage:
 * 1. Include this header in your main.c
 * 2. Call send_ir_command() with desired command timing array
 */

#ifndef MIDEA_IR_COMMANDS_H
#define MIDEA_IR_COMMANDS_H

#include <stdint.h>
#include "driver/rmt_tx.h"
#include "driver/gpio.h"

// IR Protocol Configuration
#define IR_CARRIER_FREQ_HZ    38000    // 38kHz carrier frequency
#define IR_GPIO_NUM           GPIO_NUM_18  // Change to your IR LED pin
#define IR_RESOLUTION_HZ      1000000  // 1MHz resolution for microsecond timing

// Midea AC Protocol timing (microseconds)
#define MIDEA_LEADER_PULSE    4424
#define MIDEA_LEADER_SPACE    4424
#define MIDEA_SHORT_PULSE     560
#define MIDEA_SHORT_SPACE     560
#define MIDEA_LONG_PULSE      1600    // For '1' bits
#define MIDEA_REPEAT_SPACE    5000    // Space before repeat

// Function declarations
esp_err_t ir_blaster_init(void);
esp_err_t send_ir_command(const uint32_t* timing_data, size_t count);
esp_err_t send_midea_bytes(const uint8_t* bytes, size_t count);

